Moving back to marketing

diff --git a/marketing/Dockerfile b/marketing/Dockerfile
--- a/marketing/Dockerfile
+++ b/marketing/Dockerfile
@@ -1,40 +1,59 @@
-FROM --platform=$BUILDPLATFORM node:lts-alpine as Node
+FROM node:18-alpine AS base
 
-ENV NODE_ENV=production
+# Install dependencies only when needed
+FROM base AS deps
+# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
+RUN apk add --no-cache libc6-compat
+WORKDIR /app
 
-WORKDIR /home/node/app
-RUN mkdir -p /home/node/app/node_modules && chown -R node:node /home/node/app
-RUN apk add --update python3 make g++\
-   && rm -rf /var/cache/apk/*
+# Install dependencies based on the preferred package manager
+COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
+RUN \
+  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+  elif [ -f package-lock.json ]; then npm ci; \
+  elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i --frozen-lockfile; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
 
-COPY ./package.json ./
-COPY ./package-lock.json ./
 
-RUN chown -R node:node /home/node/app
+# Rebuild the source code only when needed
+FROM base AS builder
+WORKDIR /app
+COPY --from=deps /app/node_modules ./node_modules
+COPY . .
 
-USER node
+# Next.js collects completely anonymous telemetry data about general usage.
+# Learn more here: https://nextjs.org/telemetry
+# Uncomment the following line in case you want to disable telemetry during the build.
+# ENV NEXT_TELEMETRY_DISABLED 1
 
-RUN npm i
+RUN yarn build
 
-COPY --chown=node:node ./src ./src
-COPY --chown=node:node ./tsconfig.json ./tsconfig.json
-COPY --chown=node:node ./gatsby-config.ts ./gatsby-config.ts
-COPY --chown=node:node ./gatsby-browser.ts ./gatsby-browser.ts
-COPY --chown=node:node ./gatsby-node.ts ./gatsby-node.ts
-COPY --chown=node:node ./gatsby-ssr.tsx ./gatsby-ssr.tsx
+# If using npm comment out above and use below instead
+# RUN npm run build
 
-RUN npm run build
+# Production image, copy all the files and run next
+FROM base AS runner
+WORKDIR /app
 
-FROM nginx:latest
+ENV NODE_ENV production
+# Uncomment the following line in case you want to disable telemetry during runtime.
+# ENV NEXT_TELEMETRY_DISABLED 1
 
-RUN apt update
-# RUN apt-get install nginx-extras -y
+RUN addgroup --system --gid 1001 nodejs
+RUN adduser --system --uid 1001 nextjs
 
-COPY --from=Node /home/node/app/public /usr/share/nginx/html
-COPY ./docker/nginx.conf.template /etc/nginx/conf.d/default.conf.template
-COPY ./docker/marketing-entrypoint.sh /
-# COPY ./docker/lang.lua /usr/share/nginx/lang.lua
+COPY --from=builder /app/public ./public
 
-RUN ["chmod", "+x", "/marketing-entrypoint.sh"]
-ENTRYPOINT ["/marketing-entrypoint.sh"]
-CMD ["nginx", "-g", "daemon off;"]
+# Automatically leverage output traces to reduce image size
+# https://nextjs.org/docs/advanced-features/output-file-tracing
+COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
+COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
+
+USER nextjs
+
+EXPOSE 3000
+
+ENV PORT 3000
+
+CMD ["node", "server.js"]
